POST http://18.236.212.60:80/signup HTTP/1.1
Content-Type: application/json

{
    "email": "praveen83@gmail.com",
    "username": "praveen",
    "password": "praveen88"
}

###

POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
    "email": "praveen83@gmail.com",
    "password": "praveen88"
}

###

GET http://localhost:5000/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYXZlZW44M0BnbWFpbC5jb20iLCJpYXQiOjE2NTY5Mjg5NzksImV4cCI6MTY1NjkyODk5NH0.ZwrI3J9Rp7OEnGZGlONZQGsxjc6r4Oc5JckKK1UH92o

###

POST http://localhost:5000/token HTTP/1.1
Content-Type: application/json

{
    "terraformersRefreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYXZlZW44M0BnbWFpbC5jb20iLCJpYXQiOjE2NTY5Mjg5NzB9.SjM4tiivfgSEwTtDuLSxTX6aSgrl2lhI8yoze5psctI"
}

###

DELETE http://localhost:5000/logout HTTP/1.1
Content-Type: application/json

{
    "terraformersRefreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYXZlZW44M0BnbWFpbC5jb20iLCJpYXQiOjE2NTY5Mjg5NzB9.SjM4tiivfgSEwTtDuLSxTX6aSgrl2lhI8yoze5psctI"
}

###

GET http://localhost:5000/logout HTTP/1.1
Content-Type: application/json

{
    "terraformersRefreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYXZlZW44M0BnbWFpbC5jb20iLCJpYXQiOjE2NTY5Mjg5NzB9.SjM4tiivfgSEwTtDuLSxTX6aSgrl2lhI8yoze5psctI"
}

###
# Auth 0 tests

POST https://dev-gxfk8w7z.us.auth0.com/passwordless/start HTTP/1.1
Content-Type: application/json

{
    "client_id": "WAokWY98Pim7IsbERw2gp8XfEbcwmTAn",
    "connection": "email",
    "email": "pravedino@gmail.com",
    "send": "code"
}

###

POST https://dev-gxfk8w7z.us.auth0.com/oauth/token HTTP/1.1
Content-Type: application/json

{
    "grant_type": "http://auth0.com/oauth/grant-type/passwordless/otp",
    "client_id": "WAokWY98Pim7IsbERw2gp8XfEbcwmTAn",
    "username": "pravedino@gmail.com",
    "otp": "code",
    "realm": "email",
}

###

GET http://localhost:5000/experienceDetails HTTP/1.1
Content-Type: application/json